/**
 * ManipulationFinding Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ManipulationFindingEntity } from "@chattermark/core/sources/models/index.js";
import { sourcesSchemas } from "@chattermark/core/sources";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "src";

export function createManipulationFinding(overrides: Partial<ManipulationFindingEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    detectedAt: overrides.detectedAt ?? new Date().toISOString(),
    vulnerabilityId: overrides.vulnerabilityId ?? faker.string.uuid(),
    ...overrides,
  };

  return sourcesSchemas.ManipulationFinding.parse(raw);
}

export function manipulationFindingBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createManipulationFinding(overrides));
}
