/**
 * BacktestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BacktestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BacktestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BacktestRepository,
} from "@chattermark/services/assurance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BacktestRepositoryDdb } from "./backtest-repository.ddb.js";

/**
 * BacktestRepositoryAdapter
 *
 * Implements BacktestRepository port for infrastructure layer.
 */
export class BacktestRepositoryAdapter implements BacktestRepository {
  private readonly ddb: BacktestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BacktestRepositoryDdb(this.dynamoClient);
  }

  async listBacktests(input: Parameters<BacktestRepository['listBacktests']>[0]): Promise<Awaited<ReturnType<BacktestRepository['listBacktests']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBacktests(input);
  }
}
