/**
 * EvidentiaryTimelineRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidentiaryTimelineRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing EvidentiaryTimeline repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { EvidentiaryTimelineRepository } from "@chattermark/services/assurance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * EvidentiaryTimelineRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: EVIDENTIARY_TIMELINE
 * Entity Token: EVIDENTIARY_TIMELINE
 * SK Prefix: EVIDENTIARY_TIMELINE
 */
export class EvidentiaryTimelineRepositoryDdb implements EvidentiaryTimelineRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "EVIDENTIARY_TIMELINE";
  private readonly ENTITY_TOKEN = "EVIDENTIARY_TIMELINE";
  private readonly SK_PREFIX = "EVIDENTIARY_TIMELINE";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "createdAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "ASSURANCE";
  private readonly ENTITY_TYPE_PK = "EVIDENTIARY_TIMELINES";
  private generateCorrelationId(): string {
    const domainPrefix = "asr";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async assembleEvidentiaryTimeline(input: Parameters<EvidentiaryTimelineRepository['assembleEvidentiaryTimeline']>[0]): Promise<Awaited<ReturnType<EvidentiaryTimelineRepository['assembleEvidentiaryTimeline']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!(inputExt.id ?? inputExt.id)) {
      throw new Error("Missing required parameter: id");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const pk = this.buildPK(inputExt.orgId as string, (inputExt.id ?? inputExt.id) as string);
    // Soft-delete layout prefixes SK with ACTIVE# when statusPrefix is enabled.
    const skPrefix = `${this.ENTITY_TOKEN}#${(inputExt.id ?? inputExt.id)}#`;
    const result = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      KeyConditionExpression: "PK = :pk AND begins_with(SK, :skPrefix)",
      ExpressionAttributeValues: { ":pk": pk, ":skPrefix": skPrefix },
      Limit: 1,
    });
    const item = result.Items?.[0];
    if (!item) {
      throw new Error(`${this.ENTITY_TYPE} with id ${(inputExt.id ?? inputExt.id)} not found`);
    }
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }
}
