/**
 * Repository interface for Signal
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: signals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SignalEntity
} from "../models/signal.entity.js";
import type {
  ListSignalsParams,
  Signal
} from "../types/index.js";
/**
 * SignalRepository Interface
 */
export interface SignalRepository extends CreateReadRepository<SignalEntity, Signal, string, ListSignalsParams> {

}
