/**
 * Reliability Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/sources.openapi.types.js";
import { schemas } from "../schemas/sources.schemas.js";

/**
 * Entity: ReliabilityEntity
 * Description: Represents the Reliability domain model.
 * Source: schemas.SourceReliability
 * Type: Persisted Entity (x-dynamodb)
 */
export const ReliabilityEntitySchema = schemas.SourceReliability;
export type ReliabilityEntity = components["schemas"]["SourceReliability"];
