/**
 * Source Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/sources.openapi.types.js";
import { schemas } from "../schemas/sources.schemas.js";

/**
 * Entity: SourceEntity
 * Description: Represents the Source domain model.
 * Source: schemas.Source
 * Type: Persisted Entity (x-dynamodb)
 */
export const SourceEntitySchema = schemas.Source;
export type SourceEntity = components["schemas"]["Source"];
