/**
 * Handlers for EstateItem
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EstateDomainModule } from "../dependencies/estate-ddd.dependencies.js";
import type { ListEstateItemsInput, SyncEstateItemsInput } from "@chattermark/services/estate";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/estate/items
 * Operation: listEstateItems
 */
export async function listEstateItems(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EstateDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEstateItemsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.items.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/estate/items
 * Operation: syncEstateItems
 */
export async function syncEstateItems(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EstateDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SyncEstateItemsInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.items.get.execute(input);
  return reply.code(200).send(result);
}


