/**
 * Handlers for Match
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EstateDomainModule } from "../dependencies/estate-ddd.dependencies.js";
import type { ListEstateMatchesInput } from "@chattermark/services/estate";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/estate/matches
 * Operation: listEstateMatches
 */
export async function listEstateMatches(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], vulnerabilityId?: string | string[], applicableOnly?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EstateDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEstateMatchesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.matches.list.execute(input);
  return reply.code(200).send(result);
}


