/**
 * GetAccuracyReport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAccuracyReport } from "@chattermark/api-server/domains/assurance/handlers";
import type { AssuranceDDDDependencies } from "@chattermark/api-server/domains/assurance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chattermark/tests/shared";
import { ASSURANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAccuracyReport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssuranceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssuranceDDDDependencies>(
      ASSURANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAccuracyReport, "execute").mockResolvedValue(useCaseResult);

    await getAccuracyReport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAccuracyReport.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
