/**
 * ListWarnings handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listWarnings } from "@chattermark/api-server/domains/warnings/handlers";
import type { WarningsDDDDependencies } from "@chattermark/api-server/domains/warnings";
import { createWarning as createWarningEntity } from "@chattermark/factories/warnings";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chattermark/tests/shared";
import { WARNINGS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListWarnings", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: WarningsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<WarningsDDDDependencies>(
      WARNINGS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createWarningEntity({ orgId }),
      createWarningEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListWarnings, "execute").mockResolvedValue(useCaseResult);

    await listWarnings(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListWarnings.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
