/**
 * Backtest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Backtest DTOs
 *
 * DDD: Application DTOs for Backtest use cases.
 */

import type { ListBacktestsParams } from "@chattermark/core/assurance/types";

export type ListBacktestsInput = ListBacktestsParams;

export type ListBacktestsOutput = {};
