/**
 * EvidentiaryTimeline DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidentiaryTimeline DTOs
 *
 * DDD: Application DTOs for EvidentiaryTimeline use cases.
 */

import type { AssembleEvidentiaryTimelineRequestInput } from "@chattermark/core/assurance/types";

export type AssembleEvidentiaryTimelineInput = AssembleEvidentiaryTimelineRequestInput;

export type AssembleEvidentiaryTimelineOutput = {};
