/**
 * ExecuteValidateWarning - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteValidateWarning Use Case
 *
 * DDD: Application use case for get Validation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ValidateWarningInput, ValidateWarningOutput } from "../dto/validation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chattermark/services/_shared/index.js";
import type { ValidationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteValidateWarning {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly validation: ValidationRepository
  ) {}

  async execute(input: ValidateWarningInput): Promise<ValidateWarningOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.wrnId();

    // All field names extracted from OpenAPI spec: assignedOwner, outcome, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).warningId) {
      throw new ValidationError("warningId is required");
    }
    const warningId = (input as any).warningId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.validation.validateWarning({ warningId: warningId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${warningId}`);
    }

    return entity as ValidateWarningOutput;
  }
}
