/**
 * Repository interface for AuditEvent
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AuditEventEntity
} from "../models/audit-event.entity.js";
import type {
  ListAuditEventsParams
} from "../types/index.js";
/**
 * AuditEventRepository Interface
 */
export interface AuditEventRepository extends ReadRepository<AuditEventEntity, string, ListAuditEventsParams> {

}
