/**
 * Repository interface for EscalationPolicy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EscalationPolicyEntity
} from "../models/escalation-policy.entity.js";
import type {
  UpdateEscalationPolicyRequestInput
} from "../types/index.js";
/**
 * EscalationPolicyRepository Interface
 */
export interface EscalationPolicyRepository extends UpdateReadRepository<EscalationPolicyEntity, UpdateEscalationPolicyRequestInput, string, Record<string, never>> {

}
