/**
 * Handlers for ScoringVersion
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ForecastsDomainModule } from "../dependencies/forecasts-ddd.dependencies.js";
import type { ListScoringVersionsInput } from "@chattermark/services/forecasts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/scoring-versions
 * Operation: listScoringVersions
 */
export async function listScoringVersions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ForecastsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListScoringVersionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.scoringVersions.list.execute(input);
  return reply.code(200).send(result);
}


