/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/warnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List warnings */
        get: operations["listWarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warnings/shortlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capacity-capped emergency-window shortlist */
        get: operations["getWarningShortlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warnings/{warningId}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warningId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyst validation of an issued warning */
        post: operations["validateWarning"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        Vulnerability: {
            /** @example CVE-2016-5195 */
            id: string;
            title?: string;
            vendor?: string;
            product?: string;
            /** Format: date-time */
            firstSeenOnlineAt?: string;
            /** Format: date-time */
            vendorAdvisoryAt?: string;
            /** Format: date-time */
            databasePublishedAt?: string;
        };
        Source: {
            id: string;
            handle: string;
            /** @enum {string} */
            platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
            /** @enum {string} */
            trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
            evaluatedWarnings?: number;
            suspectedInauthentic?: boolean;
        };
        Forecast: {
            vulnerabilityId: string;
            /** Format: float */
            score: number;
            /** Format: float */
            scoreAfterManipulationScreening?: number;
            independentCredibleSources?: number;
            contributingSignalIds?: string[];
            topSources?: {
                id: string;
                handle: string;
                /** @enum {string} */
                platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                /** @enum {string} */
                trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                evaluatedWarnings?: number;
                suspectedInauthentic?: boolean;
            }[];
            scoringVersion: string;
            /** Format: date-time */
            formedAt?: string;
            /** @default true */
            absenceIsNotSafety: boolean;
        };
        EstateItem: {
            assetGroupId?: string;
            vendor: string;
            product: string;
            version?: string;
            instanceCount?: number;
            /** @enum {string} */
            businessCriticality?: "low" | "medium" | "high" | "critical";
            internetFacing?: boolean;
        };
        EstateMatch: {
            vulnerabilityId: string;
            applicable: boolean;
            /** @enum {string} */
            suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
            matchedItems?: {
                assetGroupId?: string;
                vendor: string;
                product: string;
                version?: string;
                instanceCount?: number;
                /** @enum {string} */
                businessCriticality?: "low" | "medium" | "high" | "critical";
                internetFacing?: boolean;
            }[];
            affectedInstanceCount?: number;
            /** @enum {string} */
            highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
        };
        Warning: {
            id: string;
            vulnerabilityId: string;
            /** @enum {string} */
            status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
            /** Format: date-time */
            issuedAt: string;
            vulnerability?: {
                /** @example CVE-2016-5195 */
                id: string;
                title?: string;
                vendor?: string;
                product?: string;
                /** Format: date-time */
                firstSeenOnlineAt?: string;
                /** Format: date-time */
                vendorAdvisoryAt?: string;
                /** Format: date-time */
                databasePublishedAt?: string;
            };
            forecastSnapshot?: {
                vulnerabilityId: string;
                /** Format: float */
                score: number;
                /** Format: float */
                scoreAfterManipulationScreening?: number;
                independentCredibleSources?: number;
                contributingSignalIds?: string[];
                topSources?: {
                    id: string;
                    handle: string;
                    /** @enum {string} */
                    platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                    /** @enum {string} */
                    trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                    evaluatedWarnings?: number;
                    suspectedInauthentic?: boolean;
                }[];
                scoringVersion: string;
                /** Format: date-time */
                formedAt?: string;
                /** @default true */
                absenceIsNotSafety: boolean;
            };
            estateMatch?: {
                vulnerabilityId: string;
                applicable: boolean;
                /** @enum {string} */
                suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                matchedItems?: {
                    assetGroupId?: string;
                    vendor: string;
                    product: string;
                    version?: string;
                    instanceCount?: number;
                    /** @enum {string} */
                    businessCriticality?: "low" | "medium" | "high" | "critical";
                    internetFacing?: boolean;
                }[];
                affectedInstanceCount?: number;
                /** @enum {string} */
                highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
            };
            assignedOwner?: string;
            leadDaysAheadOfAdvisory?: number;
            leadDaysAheadOfPublication?: number;
            /** @enum {string} */
            analystAdjustment?: "none" | "raised" | "lowered";
            analystRationale?: string;
            withdrawalReason?: string;
        };
        WarningListData: {
            items: {
                id: string;
                vulnerabilityId: string;
                /** @enum {string} */
                status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
                /** Format: date-time */
                issuedAt: string;
                vulnerability?: {
                    /** @example CVE-2016-5195 */
                    id: string;
                    title?: string;
                    vendor?: string;
                    product?: string;
                    /** Format: date-time */
                    firstSeenOnlineAt?: string;
                    /** Format: date-time */
                    vendorAdvisoryAt?: string;
                    /** Format: date-time */
                    databasePublishedAt?: string;
                };
                forecastSnapshot?: {
                    vulnerabilityId: string;
                    /** Format: float */
                    score: number;
                    /** Format: float */
                    scoreAfterManipulationScreening?: number;
                    independentCredibleSources?: number;
                    contributingSignalIds?: string[];
                    topSources?: {
                        id: string;
                        handle: string;
                        /** @enum {string} */
                        platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                        /** @enum {string} */
                        trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                        evaluatedWarnings?: number;
                        suspectedInauthentic?: boolean;
                    }[];
                    scoringVersion: string;
                    /** Format: date-time */
                    formedAt?: string;
                    /** @default true */
                    absenceIsNotSafety: boolean;
                };
                estateMatch?: {
                    vulnerabilityId: string;
                    applicable: boolean;
                    /** @enum {string} */
                    suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                    matchedItems?: {
                        assetGroupId?: string;
                        vendor: string;
                        product: string;
                        version?: string;
                        instanceCount?: number;
                        /** @enum {string} */
                        businessCriticality?: "low" | "medium" | "high" | "critical";
                        internetFacing?: boolean;
                    }[];
                    affectedInstanceCount?: number;
                    /** @enum {string} */
                    highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
                };
                assignedOwner?: string;
                leadDaysAheadOfAdvisory?: number;
                leadDaysAheadOfPublication?: number;
                /** @enum {string} */
                analystAdjustment?: "none" | "raised" | "lowered";
                analystRationale?: string;
                withdrawalReason?: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        WarningListResponse: {
            data: {
                items: {
                    id: string;
                    vulnerabilityId: string;
                    /** @enum {string} */
                    status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
                    /** Format: date-time */
                    issuedAt: string;
                    vulnerability?: {
                        /** @example CVE-2016-5195 */
                        id: string;
                        title?: string;
                        vendor?: string;
                        product?: string;
                        /** Format: date-time */
                        firstSeenOnlineAt?: string;
                        /** Format: date-time */
                        vendorAdvisoryAt?: string;
                        /** Format: date-time */
                        databasePublishedAt?: string;
                    };
                    forecastSnapshot?: {
                        vulnerabilityId: string;
                        /** Format: float */
                        score: number;
                        /** Format: float */
                        scoreAfterManipulationScreening?: number;
                        independentCredibleSources?: number;
                        contributingSignalIds?: string[];
                        topSources?: {
                            id: string;
                            handle: string;
                            /** @enum {string} */
                            platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                            /** @enum {string} */
                            trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                            evaluatedWarnings?: number;
                            suspectedInauthentic?: boolean;
                        }[];
                        scoringVersion: string;
                        /** Format: date-time */
                        formedAt?: string;
                        /** @default true */
                        absenceIsNotSafety: boolean;
                    };
                    estateMatch?: {
                        vulnerabilityId: string;
                        applicable: boolean;
                        /** @enum {string} */
                        suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                        matchedItems?: {
                            assetGroupId?: string;
                            vendor: string;
                            product: string;
                            version?: string;
                            instanceCount?: number;
                            /** @enum {string} */
                            businessCriticality?: "low" | "medium" | "high" | "critical";
                            internetFacing?: boolean;
                        }[];
                        affectedInstanceCount?: number;
                        /** @enum {string} */
                        highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
                    };
                    assignedOwner?: string;
                    leadDaysAheadOfAdvisory?: number;
                    leadDaysAheadOfPublication?: number;
                    /** @enum {string} */
                    analystAdjustment?: "none" | "raised" | "lowered";
                    analystRationale?: string;
                    withdrawalReason?: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        Shortlist: {
            period?: string;
            declaredCapacity?: number;
            warnings?: {
                id: string;
                vulnerabilityId: string;
                /** @enum {string} */
                status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
                /** Format: date-time */
                issuedAt: string;
                vulnerability?: {
                    /** @example CVE-2016-5195 */
                    id: string;
                    title?: string;
                    vendor?: string;
                    product?: string;
                    /** Format: date-time */
                    firstSeenOnlineAt?: string;
                    /** Format: date-time */
                    vendorAdvisoryAt?: string;
                    /** Format: date-time */
                    databasePublishedAt?: string;
                };
                forecastSnapshot?: {
                    vulnerabilityId: string;
                    /** Format: float */
                    score: number;
                    /** Format: float */
                    scoreAfterManipulationScreening?: number;
                    independentCredibleSources?: number;
                    contributingSignalIds?: string[];
                    topSources?: {
                        id: string;
                        handle: string;
                        /** @enum {string} */
                        platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                        /** @enum {string} */
                        trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                        evaluatedWarnings?: number;
                        suspectedInauthentic?: boolean;
                    }[];
                    scoringVersion: string;
                    /** Format: date-time */
                    formedAt?: string;
                    /** @default true */
                    absenceIsNotSafety: boolean;
                };
                estateMatch?: {
                    vulnerabilityId: string;
                    applicable: boolean;
                    /** @enum {string} */
                    suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                    matchedItems?: {
                        assetGroupId?: string;
                        vendor: string;
                        product: string;
                        version?: string;
                        instanceCount?: number;
                        /** @enum {string} */
                        businessCriticality?: "low" | "medium" | "high" | "critical";
                        internetFacing?: boolean;
                    }[];
                    affectedInstanceCount?: number;
                    /** @enum {string} */
                    highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
                };
                assignedOwner?: string;
                leadDaysAheadOfAdvisory?: number;
                leadDaysAheadOfPublication?: number;
                /** @enum {string} */
                analystAdjustment?: "none" | "raised" | "lowered";
                analystRationale?: string;
                withdrawalReason?: string;
            }[];
            omittedWarningCount?: number;
            capacityStatement?: string;
        };
        ShortlistResponse: {
            data: {
                period?: string;
                declaredCapacity?: number;
                warnings?: {
                    id: string;
                    vulnerabilityId: string;
                    /** @enum {string} */
                    status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
                    /** Format: date-time */
                    issuedAt: string;
                    vulnerability?: {
                        /** @example CVE-2016-5195 */
                        id: string;
                        title?: string;
                        vendor?: string;
                        product?: string;
                        /** Format: date-time */
                        firstSeenOnlineAt?: string;
                        /** Format: date-time */
                        vendorAdvisoryAt?: string;
                        /** Format: date-time */
                        databasePublishedAt?: string;
                    };
                    forecastSnapshot?: {
                        vulnerabilityId: string;
                        /** Format: float */
                        score: number;
                        /** Format: float */
                        scoreAfterManipulationScreening?: number;
                        independentCredibleSources?: number;
                        contributingSignalIds?: string[];
                        topSources?: {
                            id: string;
                            handle: string;
                            /** @enum {string} */
                            platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                            /** @enum {string} */
                            trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                            evaluatedWarnings?: number;
                            suspectedInauthentic?: boolean;
                        }[];
                        scoringVersion: string;
                        /** Format: date-time */
                        formedAt?: string;
                        /** @default true */
                        absenceIsNotSafety: boolean;
                    };
                    estateMatch?: {
                        vulnerabilityId: string;
                        applicable: boolean;
                        /** @enum {string} */
                        suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                        matchedItems?: {
                            assetGroupId?: string;
                            vendor: string;
                            product: string;
                            version?: string;
                            instanceCount?: number;
                            /** @enum {string} */
                            businessCriticality?: "low" | "medium" | "high" | "critical";
                            internetFacing?: boolean;
                        }[];
                        affectedInstanceCount?: number;
                        /** @enum {string} */
                        highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
                    };
                    assignedOwner?: string;
                    leadDaysAheadOfAdvisory?: number;
                    leadDaysAheadOfPublication?: number;
                    /** @enum {string} */
                    analystAdjustment?: "none" | "raised" | "lowered";
                    analystRationale?: string;
                    withdrawalReason?: string;
                }[];
                omittedWarningCount?: number;
                capacityStatement?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        WarningId: string;
        WarningValidation: {
            /** @enum {string} */
            outcome: "confirm" | "raise" | "lower" | "withdraw";
            rationale?: string;
            assignedOwner?: string;
        };
        WarningResponse: {
            data: {
                id: string;
                vulnerabilityId: string;
                /** @enum {string} */
                status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
                /** Format: date-time */
                issuedAt: string;
                vulnerability?: {
                    /** @example CVE-2016-5195 */
                    id: string;
                    title?: string;
                    vendor?: string;
                    product?: string;
                    /** Format: date-time */
                    firstSeenOnlineAt?: string;
                    /** Format: date-time */
                    vendorAdvisoryAt?: string;
                    /** Format: date-time */
                    databasePublishedAt?: string;
                };
                forecastSnapshot?: {
                    vulnerabilityId: string;
                    /** Format: float */
                    score: number;
                    /** Format: float */
                    scoreAfterManipulationScreening?: number;
                    independentCredibleSources?: number;
                    contributingSignalIds?: string[];
                    topSources?: {
                        id: string;
                        handle: string;
                        /** @enum {string} */
                        platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                        /** @enum {string} */
                        trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                        evaluatedWarnings?: number;
                        suspectedInauthentic?: boolean;
                    }[];
                    scoringVersion: string;
                    /** Format: date-time */
                    formedAt?: string;
                    /** @default true */
                    absenceIsNotSafety: boolean;
                };
                estateMatch?: {
                    vulnerabilityId: string;
                    applicable: boolean;
                    /** @enum {string} */
                    suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                    matchedItems?: {
                        assetGroupId?: string;
                        vendor: string;
                        product: string;
                        version?: string;
                        instanceCount?: number;
                        /** @enum {string} */
                        businessCriticality?: "low" | "medium" | "high" | "critical";
                        internetFacing?: boolean;
                    }[];
                    affectedInstanceCount?: number;
                    /** @enum {string} */
                    highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
                };
                assignedOwner?: string;
                leadDaysAheadOfAdvisory?: number;
                leadDaysAheadOfPublication?: number;
                /** @enum {string} */
                analystAdjustment?: "none" | "raised" | "lowered";
                analystRationale?: string;
                withdrawalReason?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque cursor for keyset pagination. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listWarnings: {
        parameters: {
            query?: {
                /** @description Opaque cursor for keyset pagination. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                status?: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Warnings page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                vulnerabilityId: string;
                                /** @enum {string} */
                                status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
                                /** Format: date-time */
                                issuedAt: string;
                                vulnerability?: {
                                    /** @example CVE-2016-5195 */
                                    id: string;
                                    title?: string;
                                    vendor?: string;
                                    product?: string;
                                    /** Format: date-time */
                                    firstSeenOnlineAt?: string;
                                    /** Format: date-time */
                                    vendorAdvisoryAt?: string;
                                    /** Format: date-time */
                                    databasePublishedAt?: string;
                                };
                                forecastSnapshot?: {
                                    vulnerabilityId: string;
                                    /** Format: float */
                                    score: number;
                                    /** Format: float */
                                    scoreAfterManipulationScreening?: number;
                                    independentCredibleSources?: number;
                                    contributingSignalIds?: string[];
                                    topSources?: {
                                        id: string;
                                        handle: string;
                                        /** @enum {string} */
                                        platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                                        /** @enum {string} */
                                        trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                                        evaluatedWarnings?: number;
                                        suspectedInauthentic?: boolean;
                                    }[];
                                    scoringVersion: string;
                                    /** Format: date-time */
                                    formedAt?: string;
                                    /** @default true */
                                    absenceIsNotSafety: boolean;
                                };
                                estateMatch?: {
                                    vulnerabilityId: string;
                                    applicable: boolean;
                                    /** @enum {string} */
                                    suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                                    matchedItems?: {
                                        assetGroupId?: string;
                                        vendor: string;
                                        product: string;
                                        version?: string;
                                        instanceCount?: number;
                                        /** @enum {string} */
                                        businessCriticality?: "low" | "medium" | "high" | "critical";
                                        internetFacing?: boolean;
                                    }[];
                                    affectedInstanceCount?: number;
                                    /** @enum {string} */
                                    highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
                                };
                                assignedOwner?: string;
                                leadDaysAheadOfAdvisory?: number;
                                leadDaysAheadOfPublication?: number;
                                /** @enum {string} */
                                analystAdjustment?: "none" | "raised" | "lowered";
                                analystRationale?: string;
                                withdrawalReason?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getWarningShortlist: {
        parameters: {
            query?: {
                period?: string;
                capacity?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shortlist sized to declared capacity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            period?: string;
                            declaredCapacity?: number;
                            warnings?: {
                                id: string;
                                vulnerabilityId: string;
                                /** @enum {string} */
                                status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
                                /** Format: date-time */
                                issuedAt: string;
                                vulnerability?: {
                                    /** @example CVE-2016-5195 */
                                    id: string;
                                    title?: string;
                                    vendor?: string;
                                    product?: string;
                                    /** Format: date-time */
                                    firstSeenOnlineAt?: string;
                                    /** Format: date-time */
                                    vendorAdvisoryAt?: string;
                                    /** Format: date-time */
                                    databasePublishedAt?: string;
                                };
                                forecastSnapshot?: {
                                    vulnerabilityId: string;
                                    /** Format: float */
                                    score: number;
                                    /** Format: float */
                                    scoreAfterManipulationScreening?: number;
                                    independentCredibleSources?: number;
                                    contributingSignalIds?: string[];
                                    topSources?: {
                                        id: string;
                                        handle: string;
                                        /** @enum {string} */
                                        platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                                        /** @enum {string} */
                                        trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                                        evaluatedWarnings?: number;
                                        suspectedInauthentic?: boolean;
                                    }[];
                                    scoringVersion: string;
                                    /** Format: date-time */
                                    formedAt?: string;
                                    /** @default true */
                                    absenceIsNotSafety: boolean;
                                };
                                estateMatch?: {
                                    vulnerabilityId: string;
                                    applicable: boolean;
                                    /** @enum {string} */
                                    suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                                    matchedItems?: {
                                        assetGroupId?: string;
                                        vendor: string;
                                        product: string;
                                        version?: string;
                                        instanceCount?: number;
                                        /** @enum {string} */
                                        businessCriticality?: "low" | "medium" | "high" | "critical";
                                        internetFacing?: boolean;
                                    }[];
                                    affectedInstanceCount?: number;
                                    /** @enum {string} */
                                    highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
                                };
                                assignedOwner?: string;
                                leadDaysAheadOfAdvisory?: number;
                                leadDaysAheadOfPublication?: number;
                                /** @enum {string} */
                                analystAdjustment?: "none" | "raised" | "lowered";
                                analystRationale?: string;
                                withdrawalReason?: string;
                            }[];
                            omittedWarningCount?: number;
                            capacityStatement?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    validateWarning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warningId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    outcome: "confirm" | "raise" | "lower" | "withdraw";
                    rationale?: string;
                    assignedOwner?: string;
                };
            };
        };
        responses: {
            /** @description Warning after validation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            vulnerabilityId: string;
                            /** @enum {string} */
                            status: "issued" | "validated" | "escalated" | "decided" | "withdrawn";
                            /** Format: date-time */
                            issuedAt: string;
                            vulnerability?: {
                                /** @example CVE-2016-5195 */
                                id: string;
                                title?: string;
                                vendor?: string;
                                product?: string;
                                /** Format: date-time */
                                firstSeenOnlineAt?: string;
                                /** Format: date-time */
                                vendorAdvisoryAt?: string;
                                /** Format: date-time */
                                databasePublishedAt?: string;
                            };
                            forecastSnapshot?: {
                                vulnerabilityId: string;
                                /** Format: float */
                                score: number;
                                /** Format: float */
                                scoreAfterManipulationScreening?: number;
                                independentCredibleSources?: number;
                                contributingSignalIds?: string[];
                                topSources?: {
                                    id: string;
                                    handle: string;
                                    /** @enum {string} */
                                    platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                                    /** @enum {string} */
                                    trustState: "unrated" | "provisional" | "trusted" | "degraded" | "suppressed";
                                    evaluatedWarnings?: number;
                                    suspectedInauthentic?: boolean;
                                }[];
                                scoringVersion: string;
                                /** Format: date-time */
                                formedAt?: string;
                                /** @default true */
                                absenceIsNotSafety: boolean;
                            };
                            estateMatch?: {
                                vulnerabilityId: string;
                                applicable: boolean;
                                /** @enum {string} */
                                suppressionReason?: "product_not_present" | "version_not_affected" | "product_retired" | "platform_not_used";
                                matchedItems?: {
                                    assetGroupId?: string;
                                    vendor: string;
                                    product: string;
                                    version?: string;
                                    instanceCount?: number;
                                    /** @enum {string} */
                                    businessCriticality?: "low" | "medium" | "high" | "critical";
                                    internetFacing?: boolean;
                                }[];
                                affectedInstanceCount?: number;
                                /** @enum {string} */
                                highestBusinessCriticality?: "low" | "medium" | "high" | "critical";
                            };
                            assignedOwner?: string;
                            leadDaysAheadOfAdvisory?: number;
                            leadDaysAheadOfPublication?: number;
                            /** @enum {string} */
                            analystAdjustment?: "none" | "raised" | "lowered";
                            analystRationale?: string;
                            withdrawalReason?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
