/**
 * ExecuteListSignals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSignals Use Case
 *
 * DDD: Application use case for list Signal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSignalsInput, ListSignalsOutput } from "../dto/signal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chattermark/services/_shared/index.js";
import type { SignalRepository } from "../ports";

export class ExecuteListSignals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly signal: SignalRepository
  ) {}

  async execute(input: ListSignalsInput): Promise<ListSignalsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.sigId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.signal.listSignals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSignalsOutput;
  }
}
