/**
 * Forecast DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Forecast DTOs
 *
 * DDD: Application DTOs for Forecast use cases.
 */

import type { GetForecastParams, ListForecastsParams } from "@chattermark/core/forecasts/types";

export type ListForecastsInput = ListForecastsParams;

export type GetForecastInput = GetForecastParams;

export type ListForecastsOutput = {};

export type GetForecastOutput = {};
