/**
 * CompensatingControl Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CompensatingControlEntity } from "@chattermark/core/decisions/models/index.js";
import { decisionsSchemas } from "@chattermark/core/decisions";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "dec";

export function createCompensatingControl(overrides: Partial<CompensatingControlEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    decidedAt: overrides.decidedAt ?? new Date().toISOString(),
    outcome: overrides.outcome ?? "window_opened",
    owner: overrides.owner ?? faker.lorem.word(),
    warningId: overrides.warningId ?? faker.string.uuid(),
    ...overrides,
  };

  return decisionsSchemas.Decision.parse(raw);
}

export function compensatingControlBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCompensatingControl(overrides));
}
