/**
 * Reliability DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reliability DTOs
 *
 * DDD: Application DTOs for Reliability use cases.
 */

import type { GetSourceReliabilityParams } from "@chattermark/core/sources/types";

export type GetSourceReliabilityInput = GetSourceReliabilityParams;

export type GetSourceReliabilityOutput = {};
