/**
 * Warnings DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Warnings Domain Module - Composition root
 *
 * DDD: Composition root for warnings domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ShortlistRepositoryAdapter,
  ValidationRepositoryAdapter,
  WarningRepositoryAdapter,
} from "@chattermark/adapters/warnings";
import { getIdGeneratorService } from "@chattermark/adapters";
import type { AdapterDynamoDBClient } from "@chattermark/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListWarnings,
  ExecuteValidateWarning,
} from "@chattermark/services/warnings/usecases";
// Ports (interfaces)
import type {
  ShortlistRepository,
  ValidationRepository,
  WarningRepository,
} from "@chattermark/services/warnings/ports";

export interface WarningsDomainModule {
  repos: {
    shortlists: ShortlistRepository;
    validations: ValidationRepository;
    warnings: WarningRepository;
  };
  useCases: {
    validations: {
      get: ExecuteValidateWarning;
    };
    warnings: {
      list: ExecuteListWarnings;
    };
  };
}

export function buildWarningsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): WarningsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      shortlists?: ShortlistRepository;
      validations?: ValidationRepository;
      warnings?: WarningRepository;
    } = {};

    obj.shortlists = new ShortlistRepositoryAdapter(dynamoClient);
    obj.validations = new ValidationRepositoryAdapter(dynamoClient);
    obj.warnings = new WarningRepositoryAdapter(dynamoClient);
    return {
      shortlists: obj.shortlists!,
      validations: obj.validations!,
      warnings: obj.warnings!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    validations: {
      get: new ExecuteValidateWarning(executionContext, idGenerator, repos.validations),
    },
    warnings: {
      list: new ExecuteListWarnings(executionContext, idGenerator, repos.warnings),
    },
  };
  return { repos, useCases: useCases as WarningsDomainModule["useCases"] };
}
