/**
 * Handlers for Validation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { WarningsDomainModule } from "../dependencies/warnings-ddd.dependencies.js";
import type { ValidateWarningInput } from "@chattermark/services/warnings";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/warnings/{warningId}/validation
 * Operation: validateWarning
 */
export async function validateWarning(
  request: FastifyRequest<{ Params: { warningId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: WarningsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ValidateWarningInput = {
    warningId: request.params.warningId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.validations.get.execute(input);
  return reply.code(200).send(result);
}


