/**
 * Handlers for Warning
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { WarningsDomainModule } from "../dependencies/warnings-ddd.dependencies.js";
import type { ListWarningsInput } from "@chattermark/services/warnings";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/warnings
 * Operation: listWarnings
 */
export async function listWarnings(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: WarningsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListWarningsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.warnings.list.execute(input);
  return reply.code(200).send(result);
}


