/**
 * Warning Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/warnings.openapi.types.js";
import { schemas } from "../schemas/warnings.schemas.js";

/**
 * Entity: WarningEntity
 * Description: Represents the Warning domain model.
 * Source: schemas.Warning
 * Type: Persisted Entity (x-dynamodb)
 */
export const WarningEntitySchema = schemas.Warning;
export type WarningEntity = components["schemas"]["Warning"];
