/**
 * AuditEvent Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/governance.openapi.types.js";
import { schemas } from "../schemas/governance.schemas.js";

/**
 * Entity: AuditEventEntity
 * Description: Represents the AuditEvent domain model.
 * Source: schemas.AuditEvent
 * Type: Persisted Entity (x-dynamodb)
 */
export const AuditEventEntitySchema = schemas.AuditEvent;
export type AuditEventEntity = components["schemas"]["AuditEvent"];
