/**
 * EvidentiaryTimeline Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { EvidentiaryTimelineEntity } from "@chattermark/core/assurance/models/index.js";
import { assuranceSchemas } from "@chattermark/core/assurance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "asr";

export function createEvidentiaryTimeline(overrides: Partial<EvidentiaryTimelineEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    ...overrides,
  };

  return assuranceSchemas.EvidentiaryTimeline.parse(raw);
}

export function evidentiaryTimelineBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEvidentiaryTimeline(overrides));
}
