/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { manipulationFindingRoutes } from "./manipulation-finding.routes.js";
export { sourceRoutes } from "./source.routes.js";
export { reliabilityRoutes } from "./reliability.routes.js";
