/**
 * Assurance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assurance Domain Module - Composition root
 *
 * DDD: Composition root for assurance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AccuracyReportRepositoryAdapter,
  BacktestRepositoryAdapter,
  EvidentiaryTimelineRepositoryAdapter,
} from "@chattermark/adapters/assurance";
import { getIdGeneratorService } from "@chattermark/adapters";
import type { AdapterDynamoDBClient } from "@chattermark/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAssembleEvidentiaryTimeline,
  ExecuteListBacktests,
} from "@chattermark/services/assurance/usecases";
// Ports (interfaces)
import type {
  AccuracyReportRepository,
  BacktestRepository,
  EvidentiaryTimelineRepository,
} from "@chattermark/services/assurance/ports";

export interface AssuranceDomainModule {
  repos: {
    accuracyReports: AccuracyReportRepository;
    backtests: BacktestRepository;
    evidentiaryTimelines: EvidentiaryTimelineRepository;
  };
  useCases: {
    backtests: {
      list: ExecuteListBacktests;
    };
    evidentiaryTimelines: {
      get: ExecuteAssembleEvidentiaryTimeline;
    };
  };
}

export function buildAssuranceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AssuranceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      accuracyReports?: AccuracyReportRepository;
      backtests?: BacktestRepository;
      evidentiaryTimelines?: EvidentiaryTimelineRepository;
    } = {};

    obj.accuracyReports = new AccuracyReportRepositoryAdapter(dynamoClient);
    obj.backtests = new BacktestRepositoryAdapter(dynamoClient);
    obj.evidentiaryTimelines = new EvidentiaryTimelineRepositoryAdapter(dynamoClient);
    return {
      accuracyReports: obj.accuracyReports!,
      backtests: obj.backtests!,
      evidentiaryTimelines: obj.evidentiaryTimelines!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    backtests: {
      list: new ExecuteListBacktests(executionContext, idGenerator, repos.backtests),
    },
    evidentiaryTimelines: {
      get: new ExecuteAssembleEvidentiaryTimeline(executionContext, idGenerator, repos.evidentiaryTimelines),
    },
  };
  return { repos, useCases: useCases as AssuranceDomainModule["useCases"] };
}
