/**
 * ReliabilityRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReliabilityRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReliabilityRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReliabilityRepository,
} from "@chattermark/services/sources";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReliabilityRepositoryDdb } from "./reliability-repository.ddb.js";

/**
 * ReliabilityRepositoryAdapter
 *
 * Implements ReliabilityRepository port for infrastructure layer.
 */
export class ReliabilityRepositoryAdapter implements ReliabilityRepository {
  private readonly ddb: ReliabilityRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReliabilityRepositoryDdb(this.dynamoClient);
  }

  async getSourceReliability(input: Parameters<ReliabilityRepository['getSourceReliability']>[0]): Promise<Awaited<ReturnType<ReliabilityRepository['getSourceReliability']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSourceReliability(input);
  }
}
