/**
 * Governance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Governance Domain Module - Composition root
 *
 * DDD: Composition root for governance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AuditEventRepositoryAdapter,
  EscalationPolicyRepositoryAdapter,
} from "@chattermark/adapters/governance";
import { getIdGeneratorService } from "@chattermark/adapters";
import type { AdapterDynamoDBClient } from "@chattermark/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetEscalationPolicy,
  ExecuteListAuditEvents,
  ExecuteUpdateEscalationPolicy,
} from "@chattermark/services/governance/usecases";
// Ports (interfaces)
import type {
  AuditEventRepository,
  EscalationPolicyRepository,
} from "@chattermark/services/governance/ports";

export interface GovernanceDomainModule {
  repos: {
    auditEvents: AuditEventRepository;
    escalationPolicies: EscalationPolicyRepository;
  };
  useCases: {
    auditEvents: {
      list: ExecuteListAuditEvents;
    };
    escalationPolicies: {
      get: ExecuteGetEscalationPolicy;
      update: ExecuteUpdateEscalationPolicy;
    };
  };
}

export function buildGovernanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GovernanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      auditEvents?: AuditEventRepository;
      escalationPolicies?: EscalationPolicyRepository;
    } = {};

    obj.auditEvents = new AuditEventRepositoryAdapter(dynamoClient);
    obj.escalationPolicies = new EscalationPolicyRepositoryAdapter(dynamoClient);
    return {
      auditEvents: obj.auditEvents!,
      escalationPolicies: obj.escalationPolicies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    auditEvents: {
      list: new ExecuteListAuditEvents(executionContext, idGenerator, repos.auditEvents),
    },
    escalationPolicies: {
      get: new ExecuteGetEscalationPolicy(executionContext, idGenerator, repos.escalationPolicies),
      update: new ExecuteUpdateEscalationPolicy(executionContext, idGenerator, repos.escalationPolicies),
    },
  };
  return { repos, useCases: useCases as GovernanceDomainModule["useCases"] };
}
