/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @chattermark/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@chattermark/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@chattermark/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@chattermark/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@chattermark/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@chattermark/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _assurance from "./assurance/index.js";
import * as _decisions from "./decisions/index.js";
import * as _estate from "./estate/index.js";
import * as _forecasts from "./forecasts/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _signals from "./signals/index.js";
import * as _sources from "./sources/index.js";
import * as _warnings from "./warnings/index.js";

// Export as namespaces
export const _shared = __shared;
export const assurance = _assurance;
export const decisions = _decisions;
export const estate = _estate;
export const forecasts = _forecasts;
export const governance = _governance;
export const identity = _identity;
export const signals = _signals;
export const sources = _sources;
export const warnings = _warnings;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@chattermark/core"; activity.types.*
//   - Direct exports: import * from "@chattermark/core/activity/types/index.js"
//   - Direct exports: import * from "@chattermark/core/activity/repositories/index.js"
//   - Direct exports: import * from "@chattermark/core/activity/models/index.js"
//   - Direct exports: import * from "@chattermark/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Assurance Service
export { schemas as AssuranceSchemas } from "./assurance/schemas/assurance.schemas.js";

// Decisions Service
export { schemas as DecisionsSchemas } from "./decisions/schemas/decisions.schemas.js";

// Estate Service
export { schemas as EstateSchemas } from "./estate/schemas/estate.schemas.js";

// Forecasts Service
export { schemas as ForecastsSchemas } from "./forecasts/schemas/forecasts.schemas.js";

// Governance Service
export { schemas as GovernanceSchemas } from "./governance/schemas/governance.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Signals Service
export { schemas as SignalsSchemas } from "./signals/schemas/signals.schemas.js";

// Sources Service
export { schemas as SourcesSchemas } from "./sources/schemas/sources.schemas.js";

// Warnings Service
export { schemas as WarningsSchemas } from "./warnings/schemas/warnings.schemas.js";

