/**
 * ExecuteAttachCompensatingControl - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAttachCompensatingControl Use Case
 *
 * DDD: Application use case for get CompensatingControl.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AttachCompensatingControlInput, AttachCompensatingControlOutput } from "../dto/compensating-control.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chattermark/services/_shared/index.js";
import type { CompensatingControlRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAttachCompensatingControl {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly compensatingControl: CompensatingControlRepository
  ) {}

  async execute(input: AttachCompensatingControlInput): Promise<AttachCompensatingControlOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.decId();

    // All field names extracted from OpenAPI spec: assertedBy, controlType, description, expiresAt
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).decisionId) {
      throw new ValidationError("decisionId is required");
    }
    const decisionId = (input as any).decisionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.compensatingControl.attachCompensatingControl({ decisionId: decisionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${decisionId}`);
    }

    return entity as AttachCompensatingControlOutput;
  }
}
