/**
 * ExecuteUpdateEscalationPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateEscalationPolicy Use Case
 *
 * DDD: Application use case for update EscalationPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateEscalationPolicyInput, UpdateEscalationPolicyOutput } from "../dto/escalation-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chattermark/services/_shared/index.js";
import type { EscalationPolicyRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateEscalationPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly escalationPolicy: EscalationPolicyRepository
  ) {}

  async execute(input: UpdateEscalationPolicyInput): Promise<UpdateEscalationPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).id) {
      throw new ValidationError("id is required");
    }
    const idValue = (input as any).id;

    // Load existing entity
    const existing = await this.escalationPolicy.getEscalationPolicy({ id: idValue, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${idValue}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.escalationPolicy.updateEscalationPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateEscalationPolicyOutput;
  }
}
