/**
 * ListSources handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listSources } from "@chattermark/api-server/domains/sources/handlers";
import type { SourcesDDDDependencies } from "@chattermark/api-server/domains/sources";
import { createSource as createSourceEntity } from "@chattermark/factories/sources";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chattermark/tests/shared";
import { SOURCES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListSources", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SourcesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SourcesDDDDependencies>(
      SOURCES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createSourceEntity({ orgId }),
      createSourceEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListSources, "execute").mockResolvedValue(useCaseResult);

    await listSources(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListSources.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
