/**
 * Warning Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { WarningEntity } from "@chattermark/core/warnings/models/index.js";
import { warningsSchemas } from "@chattermark/core/warnings";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "wrn";

export function createWarning(overrides: Partial<WarningEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    issuedAt: overrides.issuedAt ?? new Date().toISOString(),
    status: overrides.status ?? "issued",
    vulnerabilityId: overrides.vulnerabilityId ?? faker.string.uuid(),
    ...overrides,
  };

  return warningsSchemas.Warning.parse(raw);
}

export function warningBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createWarning(overrides));
}
