/**
 * Repository interface for ScoringVersion
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: forecasts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ScoringVersionEntity
} from "../models/scoring-version.entity.js";
import type {
  ListScoringVersionsParams
} from "../types/index.js";
/**
 * ScoringVersionRepository Interface
 */
export interface ScoringVersionRepository extends ReadRepository<ScoringVersionEntity, string, ListScoringVersionsParams> {

}
