/**
 * ExecuteListForecasts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListForecasts Use Case
 *
 * DDD: Application use case for list Forecast.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListForecastsInput, ListForecastsOutput } from "../dto/forecast.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chattermark/services/_shared/index.js";
import type { ForecastRepository } from "../ports";

export class ExecuteListForecasts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly forecast: ForecastRepository
  ) {}

  async execute(input: ListForecastsInput): Promise<ListForecastsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fctId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.forecast.listForecasts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListForecastsOutput;
  }
}
