/**
 * EstateItem DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EstateItem DTOs
 *
 * DDD: Application DTOs for EstateItem use cases.
 */

import type { ListEstateItemsParams, SyncEstateItemsRequestInput } from "@chattermark/core/estate/types";

export type ListEstateItemsInput = ListEstateItemsParams;

export type SyncEstateItemsInput = SyncEstateItemsRequestInput;

export type ListEstateItemsOutput = {};

export type SyncEstateItemsOutput = {};
