/**
 * Match DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Match DTOs
 *
 * DDD: Application DTOs for Match use cases.
 */

import type { ListEstateMatchesParams } from "@chattermark/core/estate/types";

export type ListEstateMatchesInput = ListEstateMatchesParams;

export type ListEstateMatchesOutput = {};
