/**
 * CompensatingControlRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompensatingControlRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CompensatingControlRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CompensatingControlRepository,
} from "@chattermark/services/decisions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CompensatingControlRepositoryDdb } from "./compensating-control-repository.ddb.js";

/**
 * CompensatingControlRepositoryAdapter
 *
 * Implements CompensatingControlRepository port for infrastructure layer.
 */
export class CompensatingControlRepositoryAdapter implements CompensatingControlRepository {
  private readonly ddb: CompensatingControlRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CompensatingControlRepositoryDdb(this.dynamoClient);
  }

  async attachCompensatingControl(input: Parameters<CompensatingControlRepository['attachCompensatingControl']>[0]): Promise<Awaited<ReturnType<CompensatingControlRepository['attachCompensatingControl']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.attachCompensatingControl(input);
  }
}
