/**
 * DueRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DueRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DueRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DueRepository,
} from "@chattermark/services/decisions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DueRepositoryDdb } from "./due-repository.ddb.js";

/**
 * DueRepositoryAdapter
 *
 * Implements DueRepository port for infrastructure layer.
 */
export class DueRepositoryAdapter implements DueRepository {
  private readonly ddb: DueRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DueRepositoryDdb(this.dynamoClient);
  }

  async listDeferralsDue(input: Parameters<DueRepository['listDeferralsDue']>[0]): Promise<Awaited<ReturnType<DueRepository['listDeferralsDue']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDeferralsDue(input);
  }
}
