/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List signals */
        get: operations["listSignals"];
        put?: never;
        /** Ingest a practitioner signal */
        post: operations["ingestSignal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/signals/{signalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: string;
            };
            cookie?: never;
        };
        /** Get a signal */
        get: operations["getSignal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/signals/{signalId}/binding": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Resolve ambiguous vulnerability binding */
        put: operations["resolveSignalBinding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        EntityMention: {
            /** @example Adobe Flash Player */
            surfaceForm: string;
            normalisedVendor?: string;
            normalisedProduct?: string;
            /** @default true */
            maskedInScoring: boolean;
        };
        SeverityOpinion: {
            threatAsserted: boolean;
            /** Format: float */
            threatScore?: number;
            /** Format: float */
            severityScore: number;
            criteriaMatched?: ("followers_should_worry" | "easily_exploitable" | "affects_many_users")[];
            indicativePhrases?: string[];
            scoringVersion?: string;
        };
        VulnerabilityBinding: {
            /** @enum {string} */
            status: "bound" | "held_ambiguous" | "unbound";
            vulnerabilityId?: string;
            /** @enum {string} */
            method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
            linkedUrl?: string;
            identifiersFoundOnPage?: number;
            /** Format: float */
            confidence?: number;
            resolvedBy?: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        Signal: {
            id: string;
            sourceId: string;
            /** Format: date-time */
            postedAt: string;
            text: string;
            entities?: {
                /** @example Adobe Flash Player */
                surfaceForm: string;
                normalisedVendor?: string;
                normalisedProduct?: string;
                /** @default true */
                maskedInScoring: boolean;
            }[];
            opinion?: {
                threatAsserted: boolean;
                /** Format: float */
                threatScore?: number;
                /** Format: float */
                severityScore: number;
                criteriaMatched?: ("followers_should_worry" | "easily_exploitable" | "affects_many_users")[];
                indicativePhrases?: string[];
                scoringVersion?: string;
            };
            binding?: {
                /** @enum {string} */
                status: "bound" | "held_ambiguous" | "unbound";
                vulnerabilityId?: string;
                /** @enum {string} */
                method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                linkedUrl?: string;
                identifiersFoundOnPage?: number;
                /** Format: float */
                confidence?: number;
                resolvedBy?: string;
                /** Format: date-time */
                resolvedAt?: string;
            };
            nearDuplicateOf?: string;
        };
        SignalListData: {
            items: {
                id: string;
                sourceId: string;
                /** Format: date-time */
                postedAt: string;
                text: string;
                entities?: {
                    /** @example Adobe Flash Player */
                    surfaceForm: string;
                    normalisedVendor?: string;
                    normalisedProduct?: string;
                    /** @default true */
                    maskedInScoring: boolean;
                }[];
                opinion?: {
                    threatAsserted: boolean;
                    /** Format: float */
                    threatScore?: number;
                    /** Format: float */
                    severityScore: number;
                    criteriaMatched?: ("followers_should_worry" | "easily_exploitable" | "affects_many_users")[];
                    indicativePhrases?: string[];
                    scoringVersion?: string;
                };
                binding?: {
                    /** @enum {string} */
                    status: "bound" | "held_ambiguous" | "unbound";
                    vulnerabilityId?: string;
                    /** @enum {string} */
                    method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                    linkedUrl?: string;
                    identifiersFoundOnPage?: number;
                    /** Format: float */
                    confidence?: number;
                    resolvedBy?: string;
                    /** Format: date-time */
                    resolvedAt?: string;
                };
                nearDuplicateOf?: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        SignalListResponse: {
            data: {
                items: {
                    id: string;
                    sourceId: string;
                    /** Format: date-time */
                    postedAt: string;
                    text: string;
                    entities?: {
                        /** @example Adobe Flash Player */
                        surfaceForm: string;
                        normalisedVendor?: string;
                        normalisedProduct?: string;
                        /** @default true */
                        maskedInScoring: boolean;
                    }[];
                    opinion?: {
                        threatAsserted: boolean;
                        /** Format: float */
                        threatScore?: number;
                        /** Format: float */
                        severityScore: number;
                        criteriaMatched?: ("followers_should_worry" | "easily_exploitable" | "affects_many_users")[];
                        indicativePhrases?: string[];
                        scoringVersion?: string;
                    };
                    binding?: {
                        /** @enum {string} */
                        status: "bound" | "held_ambiguous" | "unbound";
                        vulnerabilityId?: string;
                        /** @enum {string} */
                        method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                        linkedUrl?: string;
                        identifiersFoundOnPage?: number;
                        /** Format: float */
                        confidence?: number;
                        resolvedBy?: string;
                        /** Format: date-time */
                        resolvedAt?: string;
                    };
                    nearDuplicateOf?: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        SignalIngest: {
            sourceHandle: string;
            /** @enum {string} */
            platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
            /** Format: date-time */
            postedAt: string;
            text: string;
            urls?: string[];
        };
        SignalResponse: {
            data: {
                id: string;
                sourceId: string;
                /** Format: date-time */
                postedAt: string;
                text: string;
                entities?: {
                    /** @example Adobe Flash Player */
                    surfaceForm: string;
                    normalisedVendor?: string;
                    normalisedProduct?: string;
                    /** @default true */
                    maskedInScoring: boolean;
                }[];
                opinion?: {
                    threatAsserted: boolean;
                    /** Format: float */
                    threatScore?: number;
                    /** Format: float */
                    severityScore: number;
                    criteriaMatched?: ("followers_should_worry" | "easily_exploitable" | "affects_many_users")[];
                    indicativePhrases?: string[];
                    scoringVersion?: string;
                };
                binding?: {
                    /** @enum {string} */
                    status: "bound" | "held_ambiguous" | "unbound";
                    vulnerabilityId?: string;
                    /** @enum {string} */
                    method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                    linkedUrl?: string;
                    identifiersFoundOnPage?: number;
                    /** Format: float */
                    confidence?: number;
                    resolvedBy?: string;
                    /** Format: date-time */
                    resolvedAt?: string;
                };
                nearDuplicateOf?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description Signal identifier */
        SignalId: string;
        VulnerabilityBindingResolve: {
            vulnerabilityId: string;
            rationale: string;
        };
        VulnerabilityBindingResponse: {
            data: {
                /** @enum {string} */
                status: "bound" | "held_ambiguous" | "unbound";
                vulnerabilityId?: string;
                /** @enum {string} */
                method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                linkedUrl?: string;
                identifiersFoundOnPage?: number;
                /** Format: float */
                confidence?: number;
                resolvedBy?: string;
                /** Format: date-time */
                resolvedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque cursor for keyset pagination. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSignals: {
        parameters: {
            query?: {
                /** @description Opaque cursor for keyset pagination. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                vulnerabilityId?: string;
                bindingStatus?: "bound" | "held_ambiguous" | "unbound";
                minSeverityOpinion?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signals page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                sourceId: string;
                                /** Format: date-time */
                                postedAt: string;
                                text: string;
                                entities?: {
                                    /** @example Adobe Flash Player */
                                    surfaceForm: string;
                                    normalisedVendor?: string;
                                    normalisedProduct?: string;
                                    /** @default true */
                                    maskedInScoring: boolean;
                                }[];
                                opinion?: {
                                    threatAsserted: boolean;
                                    /** Format: float */
                                    threatScore?: number;
                                    /** Format: float */
                                    severityScore: number;
                                    criteriaMatched?: ("followers_should_worry" | "easily_exploitable" | "affects_many_users")[];
                                    indicativePhrases?: string[];
                                    scoringVersion?: string;
                                };
                                binding?: {
                                    /** @enum {string} */
                                    status: "bound" | "held_ambiguous" | "unbound";
                                    vulnerabilityId?: string;
                                    /** @enum {string} */
                                    method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                                    linkedUrl?: string;
                                    identifiersFoundOnPage?: number;
                                    /** Format: float */
                                    confidence?: number;
                                    resolvedBy?: string;
                                    /** Format: date-time */
                                    resolvedAt?: string;
                                };
                                nearDuplicateOf?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ingestSignal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sourceHandle: string;
                    /** @enum {string} */
                    platform?: "social" | "blog" | "vendor_advisory" | "mailing_list";
                    /** Format: date-time */
                    postedAt: string;
                    text: string;
                    urls?: string[];
                };
            };
        };
        responses: {
            /** @description Signal accepted for scoring */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            sourceId: string;
                            /** Format: date-time */
                            postedAt: string;
                            text: string;
                            entities?: {
                                /** @example Adobe Flash Player */
                                surfaceForm: string;
                                normalisedVendor?: string;
                                normalisedProduct?: string;
                                /** @default true */
                                maskedInScoring: boolean;
                            }[];
                            opinion?: {
                                threatAsserted: boolean;
                                /** Format: float */
                                threatScore?: number;
                                /** Format: float */
                                severityScore: number;
                                criteriaMatched?: ("followers_should_worry" | "easily_exploitable" | "affects_many_users")[];
                                indicativePhrases?: string[];
                                scoringVersion?: string;
                            };
                            binding?: {
                                /** @enum {string} */
                                status: "bound" | "held_ambiguous" | "unbound";
                                vulnerabilityId?: string;
                                /** @enum {string} */
                                method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                                linkedUrl?: string;
                                identifiersFoundOnPage?: number;
                                /** Format: float */
                                confidence?: number;
                                resolvedBy?: string;
                                /** Format: date-time */
                                resolvedAt?: string;
                            };
                            nearDuplicateOf?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signal with opinion and binding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            sourceId: string;
                            /** Format: date-time */
                            postedAt: string;
                            text: string;
                            entities?: {
                                /** @example Adobe Flash Player */
                                surfaceForm: string;
                                normalisedVendor?: string;
                                normalisedProduct?: string;
                                /** @default true */
                                maskedInScoring: boolean;
                            }[];
                            opinion?: {
                                threatAsserted: boolean;
                                /** Format: float */
                                threatScore?: number;
                                /** Format: float */
                                severityScore: number;
                                criteriaMatched?: ("followers_should_worry" | "easily_exploitable" | "affects_many_users")[];
                                indicativePhrases?: string[];
                                scoringVersion?: string;
                            };
                            binding?: {
                                /** @enum {string} */
                                status: "bound" | "held_ambiguous" | "unbound";
                                vulnerabilityId?: string;
                                /** @enum {string} */
                                method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                                linkedUrl?: string;
                                identifiersFoundOnPage?: number;
                                /** Format: float */
                                confidence?: number;
                                resolvedBy?: string;
                                /** Format: date-time */
                                resolvedAt?: string;
                            };
                            nearDuplicateOf?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    resolveSignalBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    vulnerabilityId: string;
                    rationale: string;
                };
            };
        };
        responses: {
            /** @description Binding resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @enum {string} */
                            status: "bound" | "held_ambiguous" | "unbound";
                            vulnerabilityId?: string;
                            /** @enum {string} */
                            method: "identifier_in_text" | "identifier_in_url" | "identifier_in_linked_page" | "analyst_resolved";
                            linkedUrl?: string;
                            identifiersFoundOnPage?: number;
                            /** Format: float */
                            confidence?: number;
                            resolvedBy?: string;
                            /** Format: date-time */
                            resolvedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
