/**
 * EstateItemRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EstateItemRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EstateItemRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EstateItemRepository,
} from "@chattermark/services/estate";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EstateItemRepositoryDdb } from "./estate-item-repository.ddb.js";

/**
 * EstateItemRepositoryAdapter
 *
 * Implements EstateItemRepository port for infrastructure layer.
 */
export class EstateItemRepositoryAdapter implements EstateItemRepository {
  private readonly ddb: EstateItemRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EstateItemRepositoryDdb(this.dynamoClient);
  }

  async listEstateItems(input: Parameters<EstateItemRepository['listEstateItems']>[0]): Promise<Awaited<ReturnType<EstateItemRepository['listEstateItems']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEstateItems(input);
  }

  async syncEstateItems(input: Parameters<EstateItemRepository['syncEstateItems']>[0]): Promise<Awaited<ReturnType<EstateItemRepository['syncEstateItems']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.syncEstateItems(input);
  }
}
