/**
 * WarningRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WarningRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements WarningRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  WarningRepository,
} from "@chattermark/services/warnings";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { WarningRepositoryDdb } from "./warning-repository.ddb.js";

/**
 * WarningRepositoryAdapter
 *
 * Implements WarningRepository port for infrastructure layer.
 */
export class WarningRepositoryAdapter implements WarningRepository {
  private readonly ddb: WarningRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new WarningRepositoryDdb(this.dynamoClient);
  }

  async listWarnings(input: Parameters<WarningRepository['listWarnings']>[0]): Promise<Awaited<ReturnType<WarningRepository['listWarnings']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listWarnings(input);
  }
}
