/**
 * Handlers for AccuracyReport
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssuranceDomainModule } from "../dependencies/assurance-ddd.dependencies.js";
import type { GetAccuracyReportInput } from "@chattermark/services/assurance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/assurance/accuracy-report
 * Operation: getAccuracyReport
 */
export async function getAccuracyReport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AssuranceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAccuracyReportInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.accuracyReports.get.execute(input);
  return reply.code(200).send(result);
}


