/**
 * AccuracyReportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccuracyReportRepository Port
 *
 * DDD: Application port for accuracyreportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAccuracyReportInput, GetAccuracyReportOutput } from "../dto/accuracy-report.dto";
export interface AccuracyReportRepository {
  getAccuracyReport(input: GetAccuracyReportInput): Promise<GetAccuracyReportOutput>;
}

export type { GetAccuracyReportInput, GetAccuracyReportOutput } from "../dto/accuracy-report.dto";
