/**
 * BacktestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BacktestRepository Port
 *
 * DDD: Application port for backtestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListBacktestsInput, ListBacktestsOutput } from "../dto/backtest.dto";
export interface BacktestRepository {
  listBacktests(input: ListBacktestsInput): Promise<ListBacktestsOutput>;
}

export type { ListBacktestsInput, ListBacktestsOutput } from "../dto/backtest.dto";
