/**
 * EvidentiaryTimelineRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidentiaryTimelineRepository Port
 *
 * DDD: Application port for evidentiarytimelinerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AssembleEvidentiaryTimelineInput, AssembleEvidentiaryTimelineOutput } from "../dto/evidentiary-timeline.dto";
export interface EvidentiaryTimelineRepository {
  assembleEvidentiaryTimeline(input: AssembleEvidentiaryTimelineInput): Promise<AssembleEvidentiaryTimelineOutput>;
}

export type { AssembleEvidentiaryTimelineInput, AssembleEvidentiaryTimelineOutput } from "../dto/evidentiary-timeline.dto";
