/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/warnings/{warningId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warningId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a terminal decision on a warning */
        post: operations["createDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List decisions */
        get: operations["listDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/deferrals/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deferrals due for review */
        get: operations["listDeferralsDue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/{decisionId}/compensating-control": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decisionId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Attach a compensating control to a decision */
        put: operations["attachCompensatingControl"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WarningId: string;
        DecisionCreate: {
            /** @enum {string} */
            outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
            owner: string;
            reason?: string;
            /** Format: date */
            reviewDate?: string;
            changeRecordReference?: string;
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        Deferral: {
            decisionId: string;
            warningId?: string;
            /** Format: date */
            reviewDate: string;
            reason?: string;
            reviewCount?: number;
        };
        CompensatingControl: {
            description: string;
            /** @enum {string} */
            controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
            assertedBy: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        ChangeWindow: {
            id?: string;
            /** Format: date-time */
            scheduledStart?: string;
            /** Format: date-time */
            scheduledEnd?: string;
            emergency?: boolean;
            changeRecordReference?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        Decision: {
            id: string;
            warningId: string;
            /** @enum {string} */
            outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
            owner: string;
            reason?: string;
            /** Format: date-time */
            decidedAt: string;
            deferral?: {
                decisionId: string;
                warningId?: string;
                /** Format: date */
                reviewDate: string;
                reason?: string;
                reviewCount?: number;
            };
            compensatingControl?: {
                description: string;
                /** @enum {string} */
                controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
                assertedBy: string;
                /** Format: date-time */
                expiresAt?: string;
            };
            changeWindow?: {
                id?: string;
                /** Format: date-time */
                scheduledStart?: string;
                /** Format: date-time */
                scheduledEnd?: string;
                emergency?: boolean;
                changeRecordReference?: string;
                /** Format: date-time */
                completedAt?: string;
            };
            /** @default true */
            appendOnly: boolean;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        DecisionResponse: {
            data: {
                id: string;
                warningId: string;
                /** @enum {string} */
                outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
                owner: string;
                reason?: string;
                /** Format: date-time */
                decidedAt: string;
                deferral?: {
                    decisionId: string;
                    warningId?: string;
                    /** Format: date */
                    reviewDate: string;
                    reason?: string;
                    reviewCount?: number;
                };
                compensatingControl?: {
                    description: string;
                    /** @enum {string} */
                    controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
                    assertedBy: string;
                    /** Format: date-time */
                    expiresAt?: string;
                };
                changeWindow?: {
                    id?: string;
                    /** Format: date-time */
                    scheduledStart?: string;
                    /** Format: date-time */
                    scheduledEnd?: string;
                    emergency?: boolean;
                    changeRecordReference?: string;
                    /** Format: date-time */
                    completedAt?: string;
                };
                /** @default true */
                appendOnly: boolean;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        DecisionListData: {
            items: {
                id: string;
                warningId: string;
                /** @enum {string} */
                outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
                owner: string;
                reason?: string;
                /** Format: date-time */
                decidedAt: string;
                deferral?: {
                    decisionId: string;
                    warningId?: string;
                    /** Format: date */
                    reviewDate: string;
                    reason?: string;
                    reviewCount?: number;
                };
                compensatingControl?: {
                    description: string;
                    /** @enum {string} */
                    controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
                    assertedBy: string;
                    /** Format: date-time */
                    expiresAt?: string;
                };
                changeWindow?: {
                    id?: string;
                    /** Format: date-time */
                    scheduledStart?: string;
                    /** Format: date-time */
                    scheduledEnd?: string;
                    emergency?: boolean;
                    changeRecordReference?: string;
                    /** Format: date-time */
                    completedAt?: string;
                };
                /** @default true */
                appendOnly: boolean;
            }[];
            nextCursor?: string;
        };
        DecisionListResponse: {
            data: {
                items: {
                    id: string;
                    warningId: string;
                    /** @enum {string} */
                    outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
                    owner: string;
                    reason?: string;
                    /** Format: date-time */
                    decidedAt: string;
                    deferral?: {
                        decisionId: string;
                        warningId?: string;
                        /** Format: date */
                        reviewDate: string;
                        reason?: string;
                        reviewCount?: number;
                    };
                    compensatingControl?: {
                        description: string;
                        /** @enum {string} */
                        controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
                        assertedBy: string;
                        /** Format: date-time */
                        expiresAt?: string;
                    };
                    changeWindow?: {
                        id?: string;
                        /** Format: date-time */
                        scheduledStart?: string;
                        /** Format: date-time */
                        scheduledEnd?: string;
                        emergency?: boolean;
                        changeRecordReference?: string;
                        /** Format: date-time */
                        completedAt?: string;
                    };
                    /** @default true */
                    appendOnly: boolean;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        DeferralListData: {
            items: {
                decisionId: string;
                warningId?: string;
                /** Format: date */
                reviewDate: string;
                reason?: string;
                reviewCount?: number;
            }[];
            nextCursor?: string;
        };
        DeferralListResponse: {
            data: {
                items: {
                    decisionId: string;
                    warningId?: string;
                    /** Format: date */
                    reviewDate: string;
                    reason?: string;
                    reviewCount?: number;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        DecisionId: string;
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque cursor for keyset pagination. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warningId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
                    owner: string;
                    reason?: string;
                    /** Format: date */
                    reviewDate?: string;
                    changeRecordReference?: string;
                };
            };
        };
        responses: {
            /** @description Decision recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            warningId: string;
                            /** @enum {string} */
                            outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
                            owner: string;
                            reason?: string;
                            /** Format: date-time */
                            decidedAt: string;
                            deferral?: {
                                decisionId: string;
                                warningId?: string;
                                /** Format: date */
                                reviewDate: string;
                                reason?: string;
                                reviewCount?: number;
                            };
                            compensatingControl?: {
                                description: string;
                                /** @enum {string} */
                                controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
                                assertedBy: string;
                                /** Format: date-time */
                                expiresAt?: string;
                            };
                            changeWindow?: {
                                id?: string;
                                /** Format: date-time */
                                scheduledStart?: string;
                                /** Format: date-time */
                                scheduledEnd?: string;
                                emergency?: boolean;
                                changeRecordReference?: string;
                                /** Format: date-time */
                                completedAt?: string;
                            };
                            /** @default true */
                            appendOnly: boolean;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listDecisions: {
        parameters: {
            query?: {
                /** @description Opaque cursor for keyset pagination. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                outcome?: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decisions page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                warningId: string;
                                /** @enum {string} */
                                outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
                                owner: string;
                                reason?: string;
                                /** Format: date-time */
                                decidedAt: string;
                                deferral?: {
                                    decisionId: string;
                                    warningId?: string;
                                    /** Format: date */
                                    reviewDate: string;
                                    reason?: string;
                                    reviewCount?: number;
                                };
                                compensatingControl?: {
                                    description: string;
                                    /** @enum {string} */
                                    controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
                                    assertedBy: string;
                                    /** Format: date-time */
                                    expiresAt?: string;
                                };
                                changeWindow?: {
                                    id?: string;
                                    /** Format: date-time */
                                    scheduledStart?: string;
                                    /** Format: date-time */
                                    scheduledEnd?: string;
                                    emergency?: boolean;
                                    changeRecordReference?: string;
                                    /** Format: date-time */
                                    completedAt?: string;
                                };
                                /** @default true */
                                appendOnly: boolean;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listDeferralsDue: {
        parameters: {
            query?: {
                /** @description Opaque cursor for keyset pagination. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                onOrBefore?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deferrals due */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                decisionId: string;
                                warningId?: string;
                                /** Format: date */
                                reviewDate: string;
                                reason?: string;
                                reviewCount?: number;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    attachCompensatingControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decisionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    description: string;
                    /** @enum {string} */
                    controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
                    assertedBy: string;
                    /** Format: date-time */
                    expiresAt?: string;
                };
            };
        };
        responses: {
            /** @description Decision with control */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            warningId: string;
                            /** @enum {string} */
                            outcome: "window_opened" | "deferred" | "declined" | "mitigated_by_control";
                            owner: string;
                            reason?: string;
                            /** Format: date-time */
                            decidedAt: string;
                            deferral?: {
                                decisionId: string;
                                warningId?: string;
                                /** Format: date */
                                reviewDate: string;
                                reason?: string;
                                reviewCount?: number;
                            };
                            compensatingControl?: {
                                description: string;
                                /** @enum {string} */
                                controlType?: "network_segmentation" | "virtual_patch" | "feature_disabled" | "access_restriction" | "monitoring_only";
                                assertedBy: string;
                                /** Format: date-time */
                                expiresAt?: string;
                            };
                            changeWindow?: {
                                id?: string;
                                /** Format: date-time */
                                scheduledStart?: string;
                                /** Format: date-time */
                                scheduledEnd?: string;
                                emergency?: boolean;
                                changeRecordReference?: string;
                                /** Format: date-time */
                                completedAt?: string;
                            };
                            /** @default true */
                            appendOnly: boolean;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
