/**
 * Routes for Binding
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { resolveSignalBinding } from "../handlers/binding.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function bindingRoutes(fastify: FastifyInstance) {
  // PUT /v1/signals/{signalId}/binding (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/signals/:signalId/binding",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { signalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSignalsDependenciesForRequest();
        await resolveSignalBinding(request, reply, deps);
      });
    }
  );


}
