/**
 * EstateItem Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { EstateItemEntity } from "@chattermark/core/estate/models/index.js";
import { estateSchemas } from "@chattermark/core/estate";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "est";

export function createEstateItem(overrides: Partial<EstateItemEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    product: overrides.product ?? faker.lorem.word(),
    vendor: overrides.vendor ?? faker.lorem.word(),
    ...overrides,
  };

  return estateSchemas.EstateItem.parse(raw);
}

export function estateItemBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEstateItem(overrides));
}
