/**
 * ListWarning DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListWarningsParams } from "@chattermark/core/warnings";

export function createListWarningRequest(overrides: Partial<ListWarningsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
