/**
 * ResolveSignalBinding handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { resolveSignalBinding } from "@chattermark/api-server/domains/signals/handlers";
import type { SignalsDDDDependencies } from "@chattermark/api-server/domains/signals";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chattermark/tests/shared";
import { SIGNALS_USE_CASES } from "../__factories__/use-cases.js";

describe("ResolveSignalBinding", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SignalsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SignalsDDDDependencies>(
      SIGNALS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { signalId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeResolveSignalBinding, "execute").mockResolvedValue(useCaseResult);

    await resolveSignalBinding(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeResolveSignalBinding.execute).toHaveBeenCalledWith(expect.objectContaining({ signalId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
