/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the warnings domain.
 * Use these factories in tests to create test data.
 */

export { createValidation } from "./validation/entity/validation.entity.factory.js";
export { createWarning } from "./warning/entity/warning.entity.factory.js";
