/**
 * ExecuteListEstateMatches - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEstateMatches Use Case
 *
 * DDD: Application use case for list Match.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEstateMatchesInput, ListEstateMatchesOutput } from "../dto/match.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chattermark/services/_shared/index.js";
import type { MatchRepository } from "../ports";

export class ExecuteListEstateMatches {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly match: MatchRepository
  ) {}

  async execute(input: ListEstateMatchesInput): Promise<ListEstateMatchesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.estId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.match.listEstateMatches({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEstateMatchesOutput;
  }
}
