/**
 * MatchRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MatchRepository Port
 *
 * DDD: Application port for matchrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListEstateMatchesInput, ListEstateMatchesOutput } from "../dto/match.dto";
export interface MatchRepository {
  listEstateMatches(input: ListEstateMatchesInput): Promise<ListEstateMatchesOutput>;
}

export type { ListEstateMatchesInput, ListEstateMatchesOutput } from "../dto/match.dto";
