/**
 * Sources DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Sources Domain Module - Composition root
 *
 * DDD: Composition root for sources domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ManipulationFindingRepositoryAdapter,
  ReliabilityRepositoryAdapter,
  SourceRepositoryAdapter,
} from "@chattermark/adapters/sources";
import { getIdGeneratorService } from "@chattermark/adapters";
import type { AdapterDynamoDBClient } from "@chattermark/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetSourceReliability,
  ExecuteListManipulationFindings,
  ExecuteListSources,
} from "@chattermark/services/sources/usecases";
// Ports (interfaces)
import type {
  ManipulationFindingRepository,
  ReliabilityRepository,
  SourceRepository,
} from "@chattermark/services/sources/ports";

export interface SourcesDomainModule {
  repos: {
    manipulationFindings: ManipulationFindingRepository;
    reliabilities: ReliabilityRepository;
    sources: SourceRepository;
  };
  useCases: {
    manipulationFindings: {
      list: ExecuteListManipulationFindings;
    };
    reliabilities: {
      get: ExecuteGetSourceReliability;
    };
    sources: {
      list: ExecuteListSources;
    };
  };
}

export function buildSourcesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SourcesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      manipulationFindings?: ManipulationFindingRepository;
      reliabilities?: ReliabilityRepository;
      sources?: SourceRepository;
    } = {};

    obj.manipulationFindings = new ManipulationFindingRepositoryAdapter(dynamoClient);
    obj.reliabilities = new ReliabilityRepositoryAdapter(dynamoClient);
    obj.sources = new SourceRepositoryAdapter(dynamoClient);
    return {
      manipulationFindings: obj.manipulationFindings!,
      reliabilities: obj.reliabilities!,
      sources: obj.sources!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    manipulationFindings: {
      list: new ExecuteListManipulationFindings(executionContext, idGenerator, repos.manipulationFindings),
    },
    reliabilities: {
      get: new ExecuteGetSourceReliability(executionContext, idGenerator, repos.reliabilities),
    },
    sources: {
      list: new ExecuteListSources(executionContext, idGenerator, repos.sources),
    },
  };
  return { repos, useCases: useCases as SourcesDomainModule["useCases"] };
}
