/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@chattermark/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@chattermark/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@chattermark/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _assurance from "./assurance/index.js";
import * as _decisions from "./decisions/index.js";
import * as _estate from "./estate/index.js";
import * as _forecasts from "./forecasts/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _signals from "./signals/index.js";
import * as _sources from "./sources/index.js";
import * as _warnings from "./warnings/index.js";

// Export as namespaces
export const assurance = _assurance;
export const decisions = _decisions;
export const estate = _estate;
export const forecasts = _forecasts;
export const governance = _governance;
export const identity = _identity;
export const signals = _signals;
export const sources = _sources;
export const warnings = _warnings;
