/**
 * GetReliability DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetSourceReliabilityParams } from "@chattermark/core/sources";

export function createGetReliabilityRequest(overrides: Partial<GetSourceReliabilityParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
