/**
 * Repository interface for EvidentiaryTimeline
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EvidentiaryTimelineEntity
} from "../models/evidentiary-timeline.entity.js";
import type {
  EvidentiaryTimeline
} from "../types/index.js";
/**
 * EvidentiaryTimelineRepository Interface
 */
export interface EvidentiaryTimelineRepository extends CreateReadRepository<EvidentiaryTimelineEntity, EvidentiaryTimeline, string, Record<string, never>> {

}
