/**
 * Decisions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decisions Domain Module - Composition root
 *
 * DDD: Composition root for decisions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CompensatingControlRepositoryAdapter,
  DecisionRepositoryAdapter,
  DueRepositoryAdapter,
} from "@chattermark/adapters/decisions";
import { getIdGeneratorService } from "@chattermark/adapters";
import type { AdapterDynamoDBClient } from "@chattermark/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAttachCompensatingControl,
  ExecuteCreateDecision,
  ExecuteListDecisions,
} from "@chattermark/services/decisions/usecases";
// Ports (interfaces)
import type {
  CompensatingControlRepository,
  DecisionRepository,
  DueRepository,
} from "@chattermark/services/decisions/ports";

export interface DecisionsDomainModule {
  repos: {
    compensatingControls: CompensatingControlRepository;
    decisions: DecisionRepository;
    dues: DueRepository;
  };
  useCases: {
    compensatingControls: {
      get: ExecuteAttachCompensatingControl;
    };
    decisions: {
      create: ExecuteCreateDecision;
      list: ExecuteListDecisions;
    };
  };
}

export function buildDecisionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DecisionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      compensatingControls?: CompensatingControlRepository;
      decisions?: DecisionRepository;
      dues?: DueRepository;
    } = {};

    obj.compensatingControls = new CompensatingControlRepositoryAdapter(dynamoClient);
    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    obj.dues = new DueRepositoryAdapter(dynamoClient);
    return {
      compensatingControls: obj.compensatingControls!,
      decisions: obj.decisions!,
      dues: obj.dues!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    compensatingControls: {
      get: new ExecuteAttachCompensatingControl(executionContext, idGenerator, repos.compensatingControls),
    },
    decisions: {
      create: new ExecuteCreateDecision(executionContext, idGenerator, repos.decisions),
      list: new ExecuteListDecisions(executionContext, idGenerator, repos.decisions),
    },
  };
  return { repos, useCases: useCases as DecisionsDomainModule["useCases"] };
}
