/**
 * ExecuteListManipulationFindings - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListManipulationFindings Use Case
 *
 * DDD: Application use case for list ManipulationFinding.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListManipulationFindingsInput, ListManipulationFindingsOutput } from "../dto/manipulation-finding.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chattermark/services/_shared/index.js";
import type { ManipulationFindingRepository } from "../ports";

export class ExecuteListManipulationFindings {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly manipulationFinding: ManipulationFindingRepository
  ) {}

  async execute(input: ListManipulationFindingsInput): Promise<ListManipulationFindingsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.srcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.manipulationFinding.listManipulationFindings({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListManipulationFindingsOutput;
  }
}
