/**
 * ExecuteGetSourceReliability - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSourceReliability Use Case
 *
 * DDD: Application use case for get Reliability.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSourceReliabilityInput, GetSourceReliabilityOutput } from "../dto/reliability.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chattermark/services/_shared/index.js";
import type { ReliabilityRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetSourceReliability {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reliability: ReliabilityRepository
  ) {}

  async execute(input: GetSourceReliabilityInput): Promise<GetSourceReliabilityOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.srcId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).sourceId) {
      throw new ValidationError("sourceId is required");
    }
    const sourceId = (input as any).sourceId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.reliability.getSourceReliability({ sourceId: sourceId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${sourceId}`);
    }

    return entity as GetSourceReliabilityOutput;
  }
}
