/**
 * ForecastRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ForecastRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ForecastRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ForecastRepository,
} from "@chattermark/services/forecasts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ForecastRepositoryDdb } from "./forecast-repository.ddb.js";

/**
 * ForecastRepositoryAdapter
 *
 * Implements ForecastRepository port for infrastructure layer.
 */
export class ForecastRepositoryAdapter implements ForecastRepository {
  private readonly ddb: ForecastRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ForecastRepositoryDdb(this.dynamoClient);
  }

  async listForecasts(input: Parameters<ForecastRepository['listForecasts']>[0]): Promise<Awaited<ReturnType<ForecastRepository['listForecasts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listForecasts(input);
  }

  async getForecast(input: Parameters<ForecastRepository['getForecast']>[0]): Promise<Awaited<ReturnType<ForecastRepository['getForecast']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getForecast(input);
  }
}
