/**
 * ScoringVersionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScoringVersionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ScoringVersionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ScoringVersionRepository,
} from "@chattermark/services/forecasts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ScoringVersionRepositoryDdb } from "./scoring-version-repository.ddb.js";

/**
 * ScoringVersionRepositoryAdapter
 *
 * Implements ScoringVersionRepository port for infrastructure layer.
 */
export class ScoringVersionRepositoryAdapter implements ScoringVersionRepository {
  private readonly ddb: ScoringVersionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ScoringVersionRepositoryDdb(this.dynamoClient);
  }

  async listScoringVersions(input: Parameters<ScoringVersionRepository['listScoringVersions']>[0]): Promise<Awaited<ReturnType<ScoringVersionRepository['listScoringVersions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listScoringVersions(input);
  }
}
