/**
 * Repository interface for CompensatingControl
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CompensatingControlEntity
} from "../models/compensating-control.entity.js";
import type {
  AttachCompensatingControlRequestInput
} from "../types/index.js";
/**
 * CompensatingControlRepository Interface
 */
export interface CompensatingControlRepository extends UpdateReadRepository<CompensatingControlEntity, AttachCompensatingControlRequestInput, string, Record<string, never>> {

}
