/**
 * ManipulationFindingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ManipulationFindingRepository Port
 *
 * DDD: Application port for manipulationfindingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListManipulationFindingsInput, ListManipulationFindingsOutput } from "../dto/manipulation-finding.dto";
export interface ManipulationFindingRepository {
  listManipulationFindings(input: ListManipulationFindingsInput): Promise<ListManipulationFindingsOutput>;
}

export type { ListManipulationFindingsInput, ListManipulationFindingsOutput } from "../dto/manipulation-finding.dto";
