/**
 * ReliabilityRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReliabilityRepository Port
 *
 * DDD: Application port for reliabilityrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSourceReliabilityInput, GetSourceReliabilityOutput } from "../dto/reliability.dto";
export interface ReliabilityRepository {
  getSourceReliability(input: GetSourceReliabilityInput): Promise<GetSourceReliabilityOutput>;
}

export type { GetSourceReliabilityInput, GetSourceReliabilityOutput } from "../dto/reliability.dto";
