/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { shortlistRoutes } from "./shortlist.routes.js";
export { warningRoutes } from "./warning.routes.js";
export { validationRoutes } from "./validation.routes.js";
