/**
 * GetSourceReliability handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sources
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSourceReliability } from "@chattermark/api-server/domains/sources/handlers";
import type { SourcesDDDDependencies } from "@chattermark/api-server/domains/sources";
import { createReliability as createReliabilityEntity } from "@chattermark/factories/sources";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chattermark/tests/shared";
import { SOURCES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSourceReliability", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SourcesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SourcesDDDDependencies>(
      SOURCES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createReliabilityEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSourceReliability, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { sourceId: entity.id };

    await getSourceReliability(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSourceReliability.execute).toHaveBeenCalledWith(expect.objectContaining({ sourceId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { sourceId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSourceReliability, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSourceReliability(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
