/**
 * IngestSignal handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { ingestSignal } from "@chattermark/api-server/domains/signals/handlers";
import type { SignalsDDDDependencies } from "@chattermark/api-server/domains/signals";
import { createSignal as createSignalEntity } from "@chattermark/factories/signals";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chattermark/tests/shared";
import { SIGNALS_USE_CASES } from "../__factories__/use-cases.js";

describe("IngestSignal", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SignalsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SignalsDDDDependencies>(
      SIGNALS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createSignalEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeIngestSignal, "execute").mockResolvedValue(useCaseResult);

    await ingestSignal(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeIngestSignal.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
