/**
 * CompensatingControl DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompensatingControl DTOs
 *
 * DDD: Application DTOs for CompensatingControl use cases.
 */

import type { AttachCompensatingControlParams, AttachCompensatingControlRequestInput } from "@chattermark/core/decisions/types";

export type AttachCompensatingControlInput = AttachCompensatingControlParams & AttachCompensatingControlRequestInput;

export type AttachCompensatingControlOutput = {};
