/**
 * Decision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decision DTOs
 *
 * DDD: Application DTOs for Decision use cases.
 */

import type { CreateDecisionParams, CreateDecisionRequestInput, ListDecisionsParams } from "@chattermark/core/decisions/types";

export type CreateDecisionInput = CreateDecisionParams & CreateDecisionRequestInput;

export type ListDecisionsInput = ListDecisionsParams;

export type CreateDecisionOutput = {};

export type ListDecisionsOutput = {};
