/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Warnings Domain Use Cases
 * 
 * List of all use case names for the warnings domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const WARNINGS_USE_CASES = [
  "executeGetWarningShortlist",
  "executeListWarnings",
  "executeValidateWarning"
] as const;
