/**
 * ScoringVersionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: forecasts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScoringVersionRepository Port
 *
 * DDD: Application port for scoringversionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListScoringVersionsInput, ListScoringVersionsOutput } from "../dto/scoring-version.dto";
export interface ScoringVersionRepository {
  listScoringVersions(input: ListScoringVersionsInput): Promise<ListScoringVersionsOutput>;
}

export type { ListScoringVersionsInput, ListScoringVersionsOutput } from "../dto/scoring-version.dto";
