/**
 * Signal Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SignalEntity } from "@chattermark/core/signals/models/index.js";
import { signalsSchemas } from "@chattermark/core/signals";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "sig";

export function createSignal(overrides: Partial<SignalEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    postedAt: overrides.postedAt ?? new Date().toISOString(),
    sourceId: overrides.sourceId ?? faker.string.uuid(),
    text: overrides.text ?? faker.lorem.paragraph(),
    ...overrides,
  };

  return signalsSchemas.Signal.parse(raw);
}

export function signalBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSignal(overrides));
}
