/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decisions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the decisions domain.
 * Use these factories in tests to create test data.
 */

export { createCompensatingControl } from "./compensating-control/entity/compensating-control.entity.factory.js";
export { createDecision } from "./decision/entity/decision.entity.factory.js";
