/**
 * AuditEvent Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AuditEventEntity } from "@chattermark/core/governance/models/index.js";
import { governanceSchemas } from "@chattermark/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createAuditEvent(overrides: Partial<AuditEventEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    action: overrides.action ?? "policy_changed",
    actor: overrides.actor ?? faker.lorem.word(),
    at: overrides.at ?? new Date().toISOString(),
    ...overrides,
  };

  return governanceSchemas.AuditEvent.parse(raw);
}

export function auditEventBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAuditEvent(overrides));
}
