/**
 * EscalationPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EscalationPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EscalationPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EscalationPolicyRepository,
} from "@chattermark/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EscalationPolicyRepositoryDdb } from "./escalation-policy-repository.ddb.js";

/**
 * EscalationPolicyRepositoryAdapter
 *
 * Implements EscalationPolicyRepository port for infrastructure layer.
 */
export class EscalationPolicyRepositoryAdapter implements EscalationPolicyRepository {
  private readonly ddb: EscalationPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EscalationPolicyRepositoryDdb(this.dynamoClient);
  }

  async getEscalationPolicy(input: Parameters<EscalationPolicyRepository['getEscalationPolicy']>[0]): Promise<Awaited<ReturnType<EscalationPolicyRepository['getEscalationPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEscalationPolicy(input);
  }

  async updateEscalationPolicy(input: Parameters<EscalationPolicyRepository['updateEscalationPolicy']>[0]): Promise<Awaited<ReturnType<EscalationPolicyRepository['updateEscalationPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateEscalationPolicy(input);
  }
}
