/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./audit-event-repository.ddb.js";
export * from "./escalation-policy-repository.ddb.js";
export * from "./audit-event-repository.adapter.js";
export * from "./escalation-policy-repository.adapter.js";
