/**
 * Signal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Signal DTOs
 *
 * DDD: Application DTOs for Signal use cases.
 */

import type { GetSignalParams, IngestSignalRequestInput, ListSignalsParams } from "@chattermark/core/signals/types";

export type ListSignalsInput = ListSignalsParams;

export type IngestSignalInput = IngestSignalRequestInput;

export type GetSignalInput = GetSignalParams;

export type ListSignalsOutput = {};

export type IngestSignalOutput = {};

export type GetSignalOutput = {};
