/**
 * EstateItem Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: estate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/estate.openapi.types.js";
import { schemas } from "../schemas/estate.schemas.js";

/**
 * Entity: EstateItemEntity
 * Description: Represents the EstateItem domain model.
 * Source: schemas.EstateItem
 * Type: Domain Entity (API)
 */
export const EstateItemEntitySchema = schemas.EstateItem;
export type EstateItemEntity = components["schemas"]["EstateItem"];
